[package]
name = "desktop-client-package"
version = "0.1.0"
authors = ["moxaj <viktor.magyari92@gmail.com>"]
edition = "2018"

[dependencies]
net-client = { path = "../net-client" }
desktop-client = { path = "../desktop-client" }
