[package]
name = "game-manager-package"
version = "0.1.0"
authors = ["moxaj <viktor.magyari92@gmail.com>"]
edition = "2018"

[dependencies]
net-server = { path = "../net-server" }
game-manager = { path = "../game-manager" }
tokio = "0.2.0-alpha.4"
futures-preview = "0.3.0-alpha.18"