[package]
name = "net"
version = "0.1.0"
authors = ["moxaj <viktor.magyari92@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.4.12"
serde = { version = "1.0.99", features = ["derive"] }
bincode = "1.1.4"
tokio = "0.2.0-alpha.4"